# https://hub.docker.com/_/centos
FROM centos:latest

MAINTAINER Satoru SATOH <ssato@redhat.com>

LABEL org.label-schema.schema-version="1.0" \
    org.label-schema.name="NOF on CentOS Image" \
    org.label-schema.vendor="Satoru SATOH" \
    org.label-schema.license="MIT" \
    org.label-schema.build-date="@BUILD_DATE@" \
    org.opencontainers.image.title="NOF on CentOS Image" \
    org.opencontainers.image.vendor="Satoru SATOH" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.created="@BUILD_DATE@"

ENV PYTHONDONTWRITEBYTECODE 1
ENV FLASK_APP nof
ENV FLASK_ENV "development"
ENV FLASK_DEBUG True
ENV PYTHONPATH = .

RUN dnf update -y && \
    dnf install -y python3-pip python3-pyyaml python3-flask; \
    dnf clean all
RUN pip3 install anyconfig networkx Flask-Bootstrap Flask-WTF

COPY src/nof/ nof/
WORKDIR .

EXPOSE 5000
CMD flask run --host=0.0.0.0
