# https://hub.docker.com/_/centos
FROM centos:latest

MAINTAINER Satoru SATOH <ssato@redhat.com>

LABEL org.label-schema.schema-version="1.0" \
    org.label-schema.name="NOF on CentOS Image" \
    org.label-schema.vendor="Satoru SATOH" \
    org.label-schema.license="MIT" \
    org.label-schema.build-date="@BUILD_DATE@" \
    org.opencontainers.image.title="NOF on CentOS Image" \
    org.opencontainers.image.vendor="Satoru SATOH" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.created="@BUILD_DATE@"

RUN dnf update -y && \
    dnf install -y python3-pip python3-pyyaml python3-flask; \
    dnf clean all

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY src/ app/
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 FLASK_APP="nof" \
    FLASK_ENV="development" FLASK_DEBUG=True \
    PYTHONPATH=/app/

EXPOSE 5000
CMD FLASK_APP=nof flask run --host=0.0.0.0
